### PR TITLE
Add -nm alias

### PR DESCRIPTION
**Pull request by grantmcconnaughey**

### CODE REVIEW

**Comment by grantmcconnaughey** [comment]
Any thoughts on this?

**Comment by henriquebastos** [comment]
Can you update the PR keeping the `runtests.py` unchanged? Then I can directly merge it here and next week I can release it on pipy.

**Comment by grantmcconnaughey** [comment]
Done!

**Comment by henriquebastos** [comment]
Thank you @grantmcconnaughey 

https://pypi.python.org/pypi/django-test-without-migrations/

**Pull request merged**
